### 어드민 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "jobseek2021!",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 기업 승인
PATCH http://{{host}}/user/signup/company/32
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 회원 전체 조회
GET http://{{host}}/user?page=1
Accept: application/json
Authorization: Bearer {{accessToken}}
