### 멤버 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{member_email}}",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 다른멤버 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "member2@member.com",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 공고 지원
POST http://{{host}}/recruit/2/resume/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 지원 취소
DELETE http://{{host}}/recruit/1/resume
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 기업 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{company_email}}",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 다른기업 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "company17@company.com",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 지원한 내역 조회(멤버) => 이력서 id로 조회
GET http://{{host}}/apply/member/3
Accept: application/json
Authorization: Bearer {{accessToken}}

### 지원된 내역 조회(기업) => 공고 id로 조회
GET http://{{host}}/apply/company/1
Accept: application/json
Authorization: Bearer {{accessToken}}
