### 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{member_email}}",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 1. 게시글 등록
POST http://{{host}}/post
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "제목",
  "content": "내용",
  "tagIds": [
    1,
    2,
    9,
    13
  ]
}

### 2. 게시글 수정
PUT http://{{host}}/post/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "수정된 제목",
  "content": "수정된 내용",
  "tagIds": [
    3,
    4,
    10,
    14
  ]
}

### 3. 게시글 삭제
DELETE http://{{host}}/post/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 4. 게시글 단건 조회
GET http://{{host}}/post/9
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 5. 게시글 페이징 조회
#GET http://{{host}}/post?content=톰캣&page=0&size=3&sort=id,DESC
#GET http://{{host}}/post?page=0&size=3&sort=viewCount,DESC
#GET http://{{host}}/post?title=rest&page=0&size=3&sort=id,DESC
GET http://{{host}}/post?title=자바&page=0&size=10&sort=id,DESC
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### TODO 게시글 안의 댓글 페이징 조회
GET http://{{host}}/post/6/comments?page=0&size=5&sort=id,DESC
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 6. 댓글 등록
POST http://{{host}}/post/8/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "무야호"
}

### 7. 댓글 수정
PUT http://{{host}}/post/1/comment/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "수정한 댓글"
}

### 8. 댓글 삭제
DELETE http://{{host}}/post/1/comment/1
Accept: application/json
Authorization: Bearer {{accessToken}}

### 9. 찜하기
POST http://{{host}}/post/9/favorite
Authorization: Bearer {{accessToken}}

### 10. 찜하기 취소
DELETE http://{{host}}/post/9/favorite
Authorization: Bearer {{accessToken}}

### 11. 찜 목록 조회
GET http://{{host}}/post/favorites?page=0&size=5&sort=id,DESC
Authorization: Bearer {{accessToken}}

### 12. 댓글 좋아요
POST http://{{host}}/post/1/comment/2/favorite
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 13. 댓글 좋아요 취소
DELETE http://{{host}}/post/1/comment/2/favorite
Content-Type: application/json
Authorization: Bearer {{accessToken}}
