### 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{member_email}}",
  "password": "{{password}}"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 1. 등록
POST http://{{host}}/post
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "제목",
  "content": "내용",
  "tagIds": [1,2,9,13]
}

### 2. 수정
PUT http://{{host}}/post/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "수정된 제목",
  "content": "수정된 내용",
  "tagIds": [3,4,10,14]
}

### 3. 단건 조회
GET http://{{host}}/post/1
Content-Type: application/json

### 4. 페이징 조회
GET http://{{host}}/post/paging?page=0&size=3&sort=id,DESC
Content-Type: application/json

### 5. 삭제
DELETE http://{{host}}/post/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
