### 1-1.회원가입(기업)
POST http://localhost:8081/api/user/signup/company
Content-Type: application/json

{
  "companyName": "스피드잡스",
  "contact": "010-1234-5678",
  "email": "lsb530@naver.com",
  "homepage": "https://www.naver.com",
  "name": "보쿠",
  "password": "12341234",
  "registrationNumber": "123-45-67549",
  "role": "ROLE_COMPANY"
}

### 2.회원가입확인(이메일인증)
GET http://localhost:8081/api/user/signup/confirm/a6f5e31e-cfb2-46fc-b3cb-9c34d26489e5
Accept: application/json

### 로그인(토큰받기)
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "lsb530@naver.com",
  "password": "12341234"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 1. 공고 등록
POST http://localhost:8081/api/recruit
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "제목입니당",
  "openDate": "2020-01-02 00:00:00",
  "closeDate": "2021-12-15 00:00:00",
  "status": "PROCESS",
  "thumbnail": "Empty",
  "experience": "JUNIOR",
  "position": "PERMANENT",
  "content": "모집합니다아",
  "tagIds": [1,3]
}

### 2. 공고 수정
PUT http://localhost:8081/api/recruit/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "수정입니당",
  "openDate": "2020-02-05 00:00:00",
  "closeDate": "2021-10-15 00:00:00",
  "status": "END",
  "thumbnail": "Empty",
  "experience": "JUNIOR",
  "position": "PERMANENT",
  "content": "수정입니다아",
  "tagIds": [1,5,10,14]
}

### 3. 공고 삭제
DELETE http://localhost:8081/api/recruit/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 4. 공고 단건 조회
GET http://localhost:8081/api/recruit/1
Accept: application/json
