### 1. 멤버 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{member_email}}",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 2. 기업 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{company_email}}",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 3. 관리자 로그인
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "{{admin_email}}",
  "password": "{{password}}",
  "provider": "LOCAL"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 4. 회원가입(멤버)
POST http://{{host}}/user/signup/member
Content-Type: application/json

{
  "email": "woojin7124@naver.com",
  "name": "장우진",
  "password": "jobseekA2021!",
  "role": "ROLE_MEMBER"
}

### 5. 회원가입(기업)
POST http://{{host}}/user/signup/company
Content-Type: application/json

{
  "name": "잡부",
  "email": "woojin7124@naver.com",
  "password": "jobseekA2021!",
  "contact": "010-1234-5678",
  "role": "ROLE_GUEST",
  "companyName": "잡식컴퍼니",
  "registrationNumber": "123-45-67890",
  "homepage": "https://www.jobseek.com"
}

### 6. 이메일 인증
GET http://{{host}}/user/signup/confirm/b873c9d4-ae80-40b7-b10d-46626bced036
Content-Type: application/json
Accept: application/json

### 7. 기업회원 가입 승인(관리자)
PATCH http://{{host}}/user/signup/company/32
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 8. 토큰 재발급
GET http://{{host}}/auth/reissue
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJSRUZSRVNIX1RPS0VOIiwidXNlcklkIjoiMSIsInJvbGUiOiJST0xFX01FTUJFUiIsImlhdCI6MTYxODIwNTk1MSwiZXhwIjoxNjE5NDE1NTUxfQ.bkmbCsb5E8QD4BgczcJ99yt-2WYpNPNo9Fn2xH7ctp8
Accept: application/json

> {% client.global.set("accessToken", response.body.accessToken); %}

### 9. 회원정보 수정(멤버)
PATCH http://{{host}}/user/member/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "잡숙이",
  "nickname": "잡숙이",
  "birth": "1992-05-30",
  "contact": "010-5229-7882",
  "intro": "안냐세용",
  "gender": "M"
}

### 10. 회원정보 수정(기업)
PATCH http://{{host}}/user/company/16
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "birth": "1992-05-30",
  "contact": "010-5229-7882",
  "intro": "안냐세용",
  "nickname": "boki"
}

### 11. 회원탈퇴(본인)
DELETE http://{{host}}/user/16
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "jobseekA2021!"
}

### 12.전체조회(관라자)
GET http://{{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 13. 개인정보 조회(본인)
GET http://{{host}}/user/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}
